### ISSUE TITLE
Querying for genes in study view is broken

### ISSUE THREAD

**Issue by fedde-s** [cBioPortal/cbioportal#1480]
On [http://www.cbioportal.org/beta/study.do?cancer_study_id=brca_tcga#summary], while one or more gene symbols are selected in the textbox at the top, clicking the query button next to it does not work in Firefox, Google Chrome or Safari. The former two display a warning that a pop-up was blocked.

Oddly, when I remove the genes from the textbox and click the query button again, it does query for the genes that are no longer in the textbox.

Does anyone have an idea what’s going on and how it can be fixed?

**Comment by JiaoJiao123** [comment]
@fedde-s  yeah right. I noticed that too. Also when you change gene input, it still query for the genes I entered previously. I will look into this.

**Comment by fedde-s** [comment]
Might the change in commit 4d05de6544b5f1a4518a8e5c91b94d22695ffac5 have something to do with this issue?

**Comment by JiaoJiao123** [comment]
@fedde-s yeah maybe, I am not sure. but we want to open a new page upon clicking query.

**Comment by fedde-s** [comment]
I am not an expert, but I can imagine that it might be because `QueryByGeneUtil.addStudyViewFields()` changes the DOM between the user interaction (the click) and the attempt to open the new tab. I have not tested whether this is what’s happening though.

**Comment by JiaoJiao123** [comment]
@fedde-s yeah that's also what I am thinking. It has already been fixed in the pull request https://github.com/cBioPortal/cbioportal/pull/1482

**Comment by pieterlukasse** [comment]
this bug is back in 1.3.0:

![image](https://cloud.githubusercontent.com/assets/2900303/19341509/f0775f96-912d-11e6-90eb-ab20f0401ad9.png)

**Comment by pieterlukasse** [comment]
@JiaoJiao123 @zhx828 :point_up_2:
