### ISSUE TITLE
OncoPrint OncoKB/cancerhotspots tooltip not always showing correct information

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#1984]
Missing many hotspot flames and oncoKB target icons.

![image](https://cloud.githubusercontent.com/assets/11892704/21109005/2f6f608e-c065-11e6-927b-f2de33d03e80.png)

Also, "Zoom to fit altered cases" is no longer working.

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/issues/1984
The zoom to fit altered cases is fixed in the soon-to-be-merged minimap PR

**Comment by schultzn** [comment]
InDels, like this one in EGFR, still don't have the OncoKB annotation icon. 


![image](https://cloud.githubusercontent.com/assets/11892704/21239064/623b069c-c2d3-11e6-93bf-9c6a96b224bf.png)

**Comment by adamabeshouse** [comment]
For the current release we were only annotating missense mutations.

**Comment by adamabeshouse** [comment]
@jjgao @schultzn should I do anything about this?

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/2254

**Comment by schultzn** [comment]
DelIns variants should map to in frame events - they currently map to truncating variants

![image](https://cloud.githubusercontent.com/assets/11892704/25252676/017082a2-25ec-11e7-82b9-accb8c5a5204.png)

**Comment by jjgao** [comment]
@adamabeshouse were mutation types retrieved from database/web api or calculated in front end?

**Comment by jjgao** [comment]
@adamabeshouse looks like it's data issue. Will ping @zheins and @n1zea144
