### ISSUE TITLE
Missing Web API link from top Navigation Bar

### ISSUE THREAD

**Issue by khzhu** [cBioPortal/cbioportal#2548]
Hi, 
I merged my local branch (1.6.1) with upstream release/1.7.0 this morning and rebuilt the cbioprotal. But, when I started the cbioportal I found two things were missing:

- Web API link is missing from top navigation bar
- Patient icon next to the download button on study summary page is also missing

both items are shown up at the cbioportal beta site, could this be my own problems?
Thank you!

<img width="1632" alt="screen shot 2017-06-07 at 3 12 58 pm" src="https://user-images.githubusercontent.com/17375786/26897240-dd53c8b4-4b95-11e7-88a7-599d1ea27259.png">

**Comment by khzhu** [comment]
also, in DataSet view when mouse hovering over any of study names, the URL points to www.cbioportal.org instead of localhost.
<img width="1583" alt="screen shot 2017-06-07 at 3 40 36 pm" src="https://user-images.githubusercontent.com/17375786/26897930-36916a92-4b98-11e7-9cf7-c552a9e9b437.png">

**Comment by khzhu** [comment]
sorry, the Patient icon shows up after refresh, but the Web API link is still missing.

**Comment by alisman** [comment]
@inodb this is because of a setting, right?

**Comment by alisman** [comment]
@khzhu can you make a separate ticket for the link in DataSet view and assign to @Tamba32 .  Thanks!

**Comment by inodb** [comment]
@alisman @khzhu Yeah that's a setting. Seems to work fine here on `release-1-7-0` branch with `skin.show_web_api_tab=true`

**Comment by alisman** [comment]
So @khzhu  the icon issue is resolved?   I believe this has to do with funkiness of font files when loaded cross domain (in dev env).  Is localdev set to true in localStorage?

**Comment by khzhu** [comment]
thank you! yes, the icon shown up after refresh the page, but WEB API link is still missing and show_web_api was set to true.

> [Thu Jun 08 09:51:58 kelsyzhu@tpugh25:/Library/apache-tomcat-8.5.12/webapps/cbioportal/WEB-INF/classes]$ grep "skin.show_web_api_tab=true" portal.properties 
39:skin.show_web_api_tab=true
>

**Comment by alisman** [comment]
Did you rebuild?

**Comment by alisman** [comment]
And restart?

**Comment by khzhu** [comment]
the web_api flag was always set to true. So, I did not rebuild but restart the portal. Still missing.

**Comment by alisman** [comment]
@inodb can you check if anything else determines whether it shows?

**Comment by inodb** [comment]
Hi @khzhu sorry, but i still can't reproduce this. Maybe something funky with the merging the local branch? Do you have your code somewhere?

This heroku instance runs the code on `release-1.7.0`: https://cbioportal-release-1-7-0.herokuapp.com/. Works fine there as well. Let me know!

**Comment by khzhu** [comment]
the branch was checked out from the pughlab (https://github.com/pughlab/cbioportal.git). I can access the web_api.jsp page, just the link not show up on top bar. 
Maybe is due to the merge. How about I do another merge tomorrow and let you know if the problem still exists. Thanks a lot!

**Comment by inodb** [comment]
@khzhu Sure no problem! If that still doesn't fix it, it would be useful to have the code uploaded to a branch on github so we can take a look at it. Also note that the `release-1.7.0` branch of the `pughlab` is outdated compared to the `cbioportal` repo

**Comment by khzhu** [comment]
@inodb , thank you! the fork at pughlab is actually synced with the upstream.
`[Fri Jun 09 13:36:04 kelsyzhu@tpugh25:~/workspace/cbioportal](master) $ git fetch upstream
remote: Counting objects: 9, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 9 (delta 6), reused 9 (delta 6), pack-reused 0
Unpacking objects: 100% (9/9), done.
From https://github.com/cBioPortal/cbioportal
   7fe5389..728db26  release-1.7.0 -> upstream/release-1.7.0
[Fri Jun 09 13:39:41 kelsyzhu@tpugh25:~/workspace/cbioportal](master) $ git merge upstream/master
Already up-to-date.
`
I got a fresh copy cbioportal checked out from the pughlab fork (it is synced with upstream master branch, please see my comment above) and built the portal. Ensured the web_api flag was set to true before started the portal, and then looked from the browser, No WEB_API link either. Sorry, I would say, it was not due to the branch merge to release-1.7.0, but some codes in version 1.6.1 caused the Web_API link disappearance. 
<img width="1849" alt="screen shot 2017-06-09 at 1 47 42 pm" src="https://user-images.githubusercontent.com/17375786/26987626-46a6144a-4d1a-11e7-9d70-d65e2d786830.png">
How about you check out the code from pughlab (https://github.com/pughlab/cbioportal.git) and build it and see if the WEB_API link shows up on your side.
thanks a lot!

**Comment by inodb** [comment]
@khzhu To merge in the `release-1-7-0` branch from upstream you should type:
```
git merge upstream/release-1-7-0
```
Do note this is a release candidate, not official release yet, we are still testing.

The `master` branch is still on `1.6.1`, but even when i pull pughlab's latest master branch i still see the `web_api` link:

![screen shot 2017-06-09 at 2 32 58 pm](https://user-images.githubusercontent.com/1334004/26989308-8dad50c8-4d20-11e7-964c-b45a3775e7a9.png)

**Comment by inodb** [comment]
The auto-deploy of master branch from cbioportal is also showing web api link http://cbioportal.herokuapp.com/. Maybe if you share you `portal.properties` file that could help. Also make sure you've set `PORTAL_HOME` to correct directory

**Comment by khzhu** [comment]
@inodb PORTAL_HOME has been set
`[Fri Jun 09 14:00:16 kelsyzhu@tpugh25:/Library/apache-tomcat-8.5.12/webapps/cbioportal]$ echo $PORTAL_HOME
/Library/apache-tomcat-8.5.12/webapps/cbioportal/WEB-INF/classes/`
here is the portal.properties I used. Thanks!
[portal_properties.txt](https://github.com/cBioPortal/cbioportal/files/1064986/portal_properties.txt)

**Comment by khzhu** [comment]
Hi,
If you take a look at the follow code snippet:

<%
    //  Hide the Web API and R/MAT Tabs if the Portal Requires Authentication
    if (!GlobalProperties.usersMustAuthenticate()) {
%>

<% if (GlobalProperties.showWebApiTab()) { %>
<li class="internal">
    <a href="web_api.jsp">Web API</a>
</li>
<% } %>

The Web API link will not show up if authentication was set to true in portal.properties file. What is a desired behaviour?
Thanks!
Kelsey


On Jun 9, 2017, at 5:43 PM, alisman <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #2548<https://github.com/cBioPortal/cbioportal/issues/2548>.

**Comment by alisman** [comment]
Ah, interesting.  Yes I'm sure that is intentional and is the long standing behavior.  Is that objectionable?

**Comment by inodb** [comment]
@khzhu Well spotted! Yes, that's it. The Web API and R client don't work on the authorized portals, so that's why it's disabled.

**Comment by khzhu** [comment]
Well, it will be nice if authenticated users can also access datasets via web APIs, is it possible?
Thanks!
Kelsey
On Jun 12, 2017, at 12:20 PM, alisman <notifications@github.com<mailto:notifications@github.com>> wrote:


Ah, interesting. Yes I'm sure that is intentional and is the long standing behavior. Is that objectionable?

**Comment by khzhu** [comment]
I see. Then can we do this instead, only put the check only on showRMatlabTab?
Kelsey


<% } %>


<% if (GlobalProperties.showWebApiTab()) { %>
<li class="internal">
    <a href="web_api.jsp">Web API</a>
</li>
<% }%>
<%
    //  Hide the Web API and R/MAT Tabs if the Portal Requires Authentication
    if (!GlobalProperties.usersMustAuthenticate()) {
%>

<% if (GlobalProperties.showRMatlabTab()) { %>
<li class="internal">
    <a href="cgds_r.jsp">R/MATLAB</a>
</li>
<% } %>
<% } %>

Then we user can use api

On Jun 12, 2017, at 12:20 PM, Ino de Bruijn <notifications@github.com<mailto:notifications@github.com>> wrote:


@khzhu<https://github.com/khzhu> Well spotted! Yes, that's it. The Web API and R client don't work on the authorized portals, so that's why it's disabled.

**Comment by inodb** [comment]
@khzhu Same applies to WEB API. It is possible I guess to add instructions how to pass the authentication credentials to the endpoint (feel free to send a PR). However don't think it's worth the effort at this stage, since we are working on a new Web API, meaning the old Web API will be deprecated. Once that is made public we can add some instructions how to use it with authentication.

**Comment by khzhu** [comment]
Agree, we can wait for new Web APIs released, thank you!
Kelsey
On Jun 12, 2017, at 1:43 PM, Ino de Bruijn <notifications@github.com<mailto:notifications@github.com>> wrote:


@khzhu<https://github.com/khzhu> Same applies to WEB API. It is possible I guess to add instructions how to pass the authentication credentials to the endpoint (feel free to send a PR). However don't think it's worth the effort at this stage, since we are working on a new Web API, meaning the old Web API will be deprecated. Once that is made public we can add some instructions how to use it with authentication.
