### ISSUE TITLE
If sequenced list not available, the Mutated Gene Table and CNA Table should give error message

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#3148]
Currently, the sequenced list is mandatory for the study which is not the case for studies with only expression data. 

Suggestion to modify: Instead of hanging the whole page, the Mutated Gene Table and CNA Table should give an error message saying The sequenced list is not available for this study.

**Comment by jjgao** [comment]
@zhx828 is this fixed in the new study view?

**Comment by zhx828** [comment]
@jjgao do we still have the studies like this? I thought the sequenced list is mandatory now.

**Comment by jjgao** [comment]
Not sure. Let's close this for now.
