### ISSUE TITLE
"Checked DB schema version: (expected: 0)" in v1.11.x

### ISSUE THREAD

**Issue by fedde-s** [cBioPortal/cbioportal#3953]
When installing cBioPortal according to the instructions, configuring the server based on `portal.properties.EXAMPLE`, it's not possible to load any study data whatsoever. The cause of this is that commit c2dbde54054cc85c9a5dcb948d9d661f6adfd49b of pull request #3505 moved a property used by the data loading pipeline to a different file, without adjusting the code that looks for it in `portal.properties`.

**Comment by ersinciftci** [comment]
This is fixed in `rc` a few weeks ago.

**Comment by ersinciftci** [comment]
I guess this is a duplicated issue with https://github.com/cBioPortal/cbioportal/issues/3855

**Comment by fedde-s** [comment]
`rc` will not be released until the next major release though. It would be useful to rebase the fix and have a bugfix release for this, as it's still broken in 1.11.x. Unless 1.12.0 can be released today or tomorrow of course.

**Comment by fedde-s** [comment]
Either way, I integrated a workaround into the setup automation we use at The Hyve by re-introducing the properties to `portal.properties`, so it's no longer blocking me personally; I just thought it might be an unpleasant surprise to potential new contributors.

**Comment by pieterlukasse** [comment]
I agree it better if such fixes go via the new hotfix route (i.e. master) instead of `rc`. Was blocking for a while, but we found a workaround for now.

**Comment by romgrk** [comment]
@fedde-s I'm trying to install a new instance of the cBio portal and got stuck exactly at that point. Would you mind sharing a detailed explanation of what should be done to workaround this? Thanks!

**Comment by fedde-s** [comment]
@romgrk, until a bugfix is released, the workaround is to add these two lines to your `portal.properties` file before you (re-)run [the `mvn` command](https://github.com/cBioPortal/cbioportal/blob/v1.11.3/docs/Build-from-Source.md#building-with-maven) that builds cBioPortal from source:
```
app.version=${timestamp}
db.version=${db.version}
```
