### ISSUE TITLE
beta - plots - provide error message when data isn't available

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4480]
PDGFRA has no RPPA data in this study. If I select it in plots, I get this:
![image](https://user-images.githubusercontent.com/10508276/43008816-01df2b28-8c0a-11e8-8b1c-1674bc664bdc.png)

Instead, the download components & info button shouldn't appear, and we should display an error message that the selected data doesn't exist.

http://www.cbioportal.org/beta/index.do?cancer_study_id=lgg_tcga&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=lgg_tcga_cnaseq&gene_list=TP53%2520EGFR%2520PDGFRA%2520PTEN%2520CIC&geneset_list=%20&tab_index=tab_visualize&Action=Submit&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=lgg_tcga_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=lgg_tcga_gistic&show_samples=false&clinicallist=MUTATION_COUNT%2CFRACTION_GENOME_ALTERED%2CNO_CONTEXT_MUTATION_SIGNATURE%2CINFORMED_CONSENT_VERIFIED%2CDFS_STATUS

**Comment by adamabeshouse** [comment]
this is addressed in https://github.com/cBioPortal/cbioportal-frontend/pull/1296/files - first because the profile shouldnt appear in the list if it has no data, and second even if somehow it sneaks on (i.e. due to some data issue), then the stuff you see in that screenshot will be hidden to reveal the text below that says "No data to plot."

**Comment by tmazor** [comment]
This is still an issue - now I just see the three loading dots forever.

Go to this query:
http://www.cbioportal.org/beta/index.do?cancer_study_id=lgg_tcga&Z_SCORE_THRESHOLD=2&RPPA_SCORE_THRESHOLD=2&data_priority=0&case_set_id=lgg_tcga_cnaseq&gene_list=EGFR%2520TP53%2520CIC%2520ATRX%2520PDGFRA&geneset_list=+&tab_index=tab_visualize&Action=Submit&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=lgg_tcga_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=lgg_tcga_gistic

Click over to Plots. While EGFR is still selected, change the horizontal axis to Protein Level. Now change the gene to PDGFRA.

![image](https://user-images.githubusercontent.com/10508276/43467630-1ea17d98-94b0-11e8-909e-3949ab3c6c95.png)

If I first go to PDGFRA then Protein Level doesn't appear as an option in the Data Type menu, which is good. But the order I described here is a reasonable thing for a user to do and should result in a "data not available" (or something like that) message.

**Comment by adamabeshouse** [comment]
interestingly this is precisely the scenario I was referring to in https://github.com/cBioPortal/cbioportal/issues/4538

**Comment by jjgao** [comment]
This is getting too complex. Maybe we should not be too smart about changing the dropdown menu items and simply show a message on the right that we don't have data in xx profile for xx gene?

**Comment by tmazor** [comment]
Agreed this is getting very complicated. I think JJ's suggestion above is the way to go. We can list all profiles that have data for any of the queried genes and then if the user selects a profile/gene combination that doesn't have data, we show a message where the plot would otherwise appear saying that the data doesn't exist.

**Comment by adamabeshouse** [comment]
that's already done so once we no longer filter by data availability we'll be good. im closing this because its handled in https://github.com/cBioPortal/cbioportal/issues/4538
