### ISSUE TITLE
"Profiled in ..." track should not be displayed automatically of all samples are profiled

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4569]
http://www.cbioportal.org/beta/index.do?session_id=5b636bb4498eb8b3d56738b6

![image](https://user-images.githubusercontent.com/840895/43609641-9cda6c74-9672-11e8-9a12-2b543430d0df.png)

**Comment by jjgao** [comment]
Not fixed in production. I'll verify once it's released.

**Comment by adamabeshouse** [comment]
seems fixed in both production and beta

**Comment by jjgao** [comment]
@adamabeshouse it is still happening when a gene is not sequenced in sample.

http://www.cbioportal.org/index.do?session_id=5b9ff34a498eb8b3d567e3b8
