### ISSUE TITLE
study view - bugs when adding/removing charts while filter is applied

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5562]
Go to MSK Impact study view: http://www.cbioportal.org/study?id=msk_impact_2017
Select Breast Cancer
Add "Metastatic Site" chart
--> problem 1: it adds as a pie chart, but should add as a table since there are >20 values
Click the "x" on the Metastatic Site pie chart to remove it.
Click "Clear All Filters"
--> problem 2: when the page reloads without the filter, the Metastatic Site chart appears

**Comment by jjgao** [comment]
@zhx828 I think both issues were reported. Could you link them?

**Comment by jjgao** [comment]
... and fix them :)

**Comment by zhx828** [comment]
Hm I can't reproduce the issue though. @jjgao can you?

**Comment by zhx828** [comment]
The first issue was solved a while ago.

**Comment by jjgao** [comment]
both seem fixed. I was able to reproduce a few hours ago... closing

**Comment by tmazor** [comment]
This is still happening for me - I've tested chrome & safari and both issues happen in both browsers

**Comment by jjgao** [comment]
hmm.. strange. I tried again and had the same issues. But after refreshing, the issues were gone.

**Comment by tmazor** [comment]
weird... even with a hard refresh, it happens consistently for me.

**Comment by jjgao** [comment]
hmm.. I am wondering if we have some inconsistency between the two servers. @inodb is deploying the new version. Let's try after that.

**Comment by tmazor** [comment]
I just tried and I still see both issues

**Comment by jjgao** [comment]
@tmazor could you try in another browser or in incognito? Trying to figure out if it's caching issue.

**Comment by tmazor** [comment]
I just tried incognito mode in chrome & safari and it happens in both

**Comment by jjgao** [comment]
This is very strange. @zhx828 any thoughts?

**Comment by zhx828** [comment]
@jjgao I was thinking the same thing. The latest code was not deployed to both servers. But at the time Tali tested yesterday 3pm. We have redeployed all wars to both servers. And the second issue on this ticket, it looks like a side effect of the first issue. But the thing is I tried both Chrome and Safari several times. I can't reproduce the issue.

**Comment by zhx828** [comment]
@tmazor @jjgao this issue is now solved and deployed.
