### ISSUE TITLE
MSK Whole Slide Viewer not appearing in studies besides mskimpact

### ISSUE THREAD

**Issue by n1zea144** [cBioPortal/cbioportal#6879]
There are MSK studies outside of IMPACT that contain IMPACT patients.  Some of these patients have path slides, but the appearance of the Tissue Image tab on the patient view is linked to the mskimpact study id.  Here is one such study/patient:

[https://cbioportal.mskcc.org/patient?studyId=msk_spectrum&caseId=P-0039384#navCaseIds=msk_spectrum:P-0039384](https://cbioportal.mskcc.org/patient?studyId=msk_spectrum&caseId=P-0039384#navCaseIds=msk_spectrum:P-0039384)

[https://cbioportal.mskcc.org/patient?studyId=mskimpact&caseId=P-0039384#navCaseIds=mskimpact:P-0039384](https://cbioportal.mskcc.org/patient?studyId=mskimpact&caseId=P-0039384#navCaseIds=mskimpact:P-0039384)

Can this line be relaxed to show the slide viewer when there are whole slide viewer ids available?

[https://github.com/cBioPortal/cbioportal-frontend/blob/master/src/pages/patientView/PatientViewPage.tsx#L645](https://github.com/cBioPortal/cbioportal-frontend/blob/master/src/pages/patientView/PatientViewPage.tsx#L645)

**Comment by jjgao** [comment]
@n1zea144 I am curiouos - was this a request from other investigators?

@alisman maybe we can remove the constraint about studies and rely on whether the clinical attribute exists?

@n1zea144 @ritikakundra you would need to add the clinical attributes if not already done.

**Comment by ritikakundra** [comment]
@jjgao yes this is for MSK-Spectrum.

**Comment by ritikakundra** [comment]
@jjgao the data is already in the study as clinical attributes as these are impact cases. So all impact data including slides IDs were pulled into the spectrum cohort.

**Comment by jjgao** [comment]
I think this is fixed, isn't it?

**Comment by ritikakundra** [comment]
@jjgao I still don't see it:
https://cbioportal.mskcc.org/patient?sampleId=P-0039615-T01-IM6&studyId=msk_spectrum
Vs IMPACT:
https://cbioportal.mskcc.org/patient?studyId=mskimpact&caseId=P-0039615#navCaseIds=mskimpact:P-0039615
