### ISSUE TITLE
Mouse seed database 2.12.3: cancer types and gene names not found

### ISSUE THREAD

**Issue by NikdAK** [cBioPortal/cbioportal#7372]
Hi, 
I recently switched to seed-cbioportal_mm10_v2.12.3 and now I have problems with the data validation. Previously I was working with 2.3.1, which was working fine.

First of all there is a problem with the cancer types:

```
ERROR: cancer_type_data.txt: line 1: column 5: Unknown parent for cancer type 'pdac'; value encountered: 'Pancreas'
INFO: cancer_type_data.txt: line 1: New disease type will be added to the portal; value encountered: 'pdac'
INFO: cancer_type_data.txt: Validation of file complete
INFO: cancer_type_data.txt: Read 1 lines. Lines with warning: 0. Lines with error: 1
ERROR: -: Cancer type of study is neither known to the portal nor defined in a cancer_type file; value encountered: 'pdac'

```

After I changed the value to "tissue" as a wildcard, this step continues without problems. 
Anyways I soon run into the next problem regarding gene names:

```
Reading data from:  /study/expression_data.txt
Recaching...
Finished recaching...
--> profile id:  1
--> profile name:  A name for the expression data
--> genetic alteration type:  MRNA_EXPRESSION
--> total number of samples: 2
--> total number of data lines:  35413
--> records inserted into `sample_profile` table: 2
--> total number of data entries skipped (see table below):  35413
org.mskcc.cbio.portal.dao.DaoException: Something has gone wrong!  I did not save any records to the database!
at org.mskcc.cbio.portal.scripts.ImportTabDelimData.importData(ImportTabDelimData.java:281)
at org.mskcc.cbio.portal.scripts.ImportProfileData.run(ImportProfileData.java:109)
at org.mskcc.cbio.portal.scripts.ConsoleRunnable.runInConsole(ConsoleRunnable.java:145)
at org.mskcc.cbio.portal.scripts.ImportProfileData.main(ImportProfileData.java:134)

Warnings / Errors:
-------------------
0.  CDC2        983 in config file [resources/gene_symbol_disambiguation.txt]is not valid. You should either update this file or update th   e `gene` and `gene_alias` tables to fix this.; 1x
1.  Entrez_Id null not found. Record will be skipped for this gene.; 35413x
2.  MLL2        8085 in config file [resources/gene_symbol_disambiguation.txt]is not valid. You should either update this file or update t   he `gene` and `gene_alias` tables to fix this.; 1x

ABORTED!
java.lang.RuntimeException: org.mskcc.cbio.portal.dao.DaoException: Something has gone wrong!  I did not save any records to the database!

```

If I rerun this with a debug set with Entrez IDs (mixed mouse and human just in case) the results is almost the same:
```
1.  Entrez_Id 67437 not found. Record will be skipped for this gene.; 1x
2.  Entrez_Id 6746 not found. Record will be skipped for this gene.; 1x
3.  Entrez_Id 6747 not found. Record will be skipped for this gene.; 1x
```

Can it be, that the value lookup tables in the seed databas are incomplete? Or am I doing something wrong with the commands? 

This is how I run the import:
```
docker run -it --rm --net cbio-net \
    -v /home/username/Documents/cbioportal_IMOdb/portal.properties:/cbioportal/portal.properties:ro \
    -v "/mnt/3TBVol/cbioportal_IMOdb_data/ExampleStudy1:/study:ro" \
    -v "/home/username/Documents/cbioportal_IMOdb/upload_reports:/report" \
    cbioportal/cbioportal:latest \
    metaImport.py -u http://cbioportal-container:8080 -s /study --html=/report/report.html \
	-species mouse -ucsc mm10 -ncbi 38 \
	--override_warning	
```

Thank you very much!

**Comment by jjgao** [comment]
Hi @NikdAK the error should be fixed with https://github.com/cBioPortal/cbioportal/pull/7375.

**Comment by NikdAK** [comment]
Hi @jjgao, thanks for the efforts! Are there any new on this subject? 
Also will this fix the "Unknown parent for cancer type" issue?

**Comment by NikdAK** [comment]
Hi,
thank for the update. I see that you MLL2 and CDC2 to the gene_symbol_disambiguation. 

But after updating (full uninstall and new docker runs) and migration to 2.12.4 the main issue still persists:

1) no genes recognized
```
WARNING: copynumber_discrete_data.txt: lines [2, 3, 4, (55913 more)]: Gene symbol not known to the cBioPortal instance. This record will not be      loaded.;
INFO: copynumber_continous_data.txt: Read 55917 lines. Lines with warning: 55917. Lines with error: 0
```

or

```
WARNING: protein_MS_data.txt: lines [2, 3, 4, (5420 more)]: Gene symbol not known to the cBioPortal instance. This record will not be loaded.; v     alues encountered: ['CUL4B', 'DHX8', '(5516 more)']
INFO: protein_MS_data.txt: Validation of file complete
INFO: protein_MS_data.txt: Read 5424 lines. Lines with warning: 5423. Lines with error: 0
```

2) cancer type not recognized
```
ERROR: cancer_type_data.txt: line 1: column 5: Unknown parent for cancer type 'pdac'; value encountered: 'Pancreas'
INFO: cancer_type_data.txt: line 1: New disease type will be added to the portal; value encountered: 'pdac'
INFO: cancer_type_data.txt: Validation of file complete
INFO: cancer_type_data.txt: Read 1 lines. Lines with warning: 0. Lines with error: 1
ERROR: -: Cancer type of study is neither known to the portal nor defined in a cancer_type file; value encountered: 'pdac'
```

This was no issue while using seed-cbioportal_mm10_v2.3.1.sql.gz

Thank you very much!
Cheers

**Comment by jjgao** [comment]
For 1, It is possible that the gene symbols you are using are out of date. Adding the entrez gene IDs in the data file may solve the issue.

For 2, please follow https://docs.cbioportal.org/5.1-data-loading/data-loading/file-formats#cancer-type
