### ISSUE TITLE
mutations tab oncokb annotations for structural variant partners

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#8475]
https://bit.ly/31vlWcn

ALK-EML4 are annotated with OncoKB when viewing ALK:
![image](https://user-images.githubusercontent.com/10508276/113048392-7c238780-9170-11eb-91b5-5ef6a27c5b43.png)

But annotation column is blank when viewing EML4:
![image](https://user-images.githubusercontent.com/10508276/113048437-88a7e000-9170-11eb-9c3e-550527a89246.png)

It's the same fusions, so we should see the same annotation regardless of which gene is selected.

Also, looking at EML4 in the same query on prod completely fails to load - select EML4 at this link:
https://www.cbioportal.org/results/mutations?plots_horz_selection=%7B%22dataType%22%3A%22MUTATION_EXTENDED%22%7D&plots_vert_selection=%7B%22dataType%22%3A%22MUTATION_EXTENDED%22%7D&plots_coloring_selection=%7B%7D&tab_index=tab_visualize&Action=Submit&session_id=60636dfae4b015b63e9e3665&hide_unprofiled_samples=false
Filtering to 'Fusion' for ALK also causes the page to fail on prod.
Not sure if those are larger issues that need to be fixed, or if the SV update is sufficient to address it (since all of this is working on beta portal)

**Comment by jjgao** [comment]
EML4-ALK fusion is corrected annotated as oncogenic for the [ELM4 tab](https://bit.ly/2PvawD4), but it was annotated as "not annotated in OncoKB". 

![image](https://user-images.githubusercontent.com/840895/113354000-7b275d00-930c-11eb-9cf2-4c14030de101.png)

I think we should change the logic for fusions in cbioportal. As long as one of the two genes is annotated in oncokb, we should show the evidence.

**Comment by jjgao** [comment]
cc'ing @zhx828

**Comment by tmazor** [comment]
@kalletlak I'm still seeing this issue - is the fix just not up on beta yet?

**Comment by kalletlak** [comment]
@tmazor should be in beta now.
